# Generated by Django 5.2 on 2025-05-08 21:22

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_groups(apps, schema_editor):
    # Create groups
    Group.objects.get_or_create(name="Sales")
    Group.objects.get_or_create(name="Operations")
    Group.objects.get_or_create(name="Collections")

    # Assign permissions
    # Sales permissions
    client_content_type = ContentType.objects.get(app_label="clients", model="client")
    client_view_perm = Permission.objects.get(
        codename="view_client", content_type=client_content_type
    )
    client_add_perm = Permission.objects.get(
        codename="add_client", content_type=client_content_type
    )

    sales_group = Group.objects.get(name="Sales")
    sales_group.permissions.add(client_view_perm, client_add_perm)

    # Operations permissions
    vehicle_content_type = ContentType.objects.get(
        app_label="vehicles", model="vehicle"
    )
    vehicle_view_perm = Permission.objects.get(
        codename="view_vehicle", content_type=vehicle_content_type
    )
    vehicle_add_perm = Permission.objects.get(
        codename="add_vehicle", content_type=vehicle_content_type
    )

    operations_group = Group.objects.get(name="Operations")
    operations_group.permissions.add(vehicle_view_perm, vehicle_add_perm)

    # Collections permissions
    contracts_content_type = ContentType.objects.get(
        app_label="contracts", model="contract"
    )
    contracts_view_perm = Permission.objects.get(
        codename="view_contract", content_type=contracts_content_type
    )
    contracts_add_perm = Permission.objects.get(
        codename="add_contract", content_type=contracts_content_type
    )

    collections_group = Group.objects.get(name="Collections")
    collections_group.permissions.add(contracts_view_perm, contracts_add_perm)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("clients", "0001_initial"),
        ("vehicles", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
